const Erros = {
    USUARIO_JA_EXISTENTE: "USUARIO_JA_EXISTENTE",
    USUARIO_NAO_EXISTENTE: "USUARIO_NAO_EXISTENTE",
    SENHA_OBRIGATORIA: "SENHA_OBRIGATORIA",
    SENHA_INCORRETA: "SENHA_INCORRETA"
}

export default Erros;